-- MySQL Script generated by MySQL Workbench
-- 03/10/15 13:50:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema correo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `correo` ;

-- -----------------------------------------------------
-- Schema correo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `correo` DEFAULT CHARACTER SET latin1 ;
USE `correo` ;

-- -----------------------------------------------------
-- Table `correo`.`tipo_documentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`tipo_documentos` ;

CREATE TABLE IF NOT EXISTS `correo`.`tipo_documentos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`documentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`documentos` ;

CREATE TABLE IF NOT EXISTS `correo`.`documentos` (
  `id` VARCHAR(10) NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  `bop` TINYINT(1) NULL DEFAULT '0',
  `descripcion` VARCHAR(240) NULL DEFAULT NULL,
  `recurso` LONGTEXT NULL DEFAULT NULL,
  `cab` LONGTEXT NULL DEFAULT NULL,
  `pie` LONGTEXT NULL DEFAULT NULL,
  `text_cab` LONGTEXT NULL DEFAULT NULL,
  `text_pie` LONGTEXT NULL DEFAULT NULL,
  `text_cue` LONGTEXT NULL DEFAULT NULL,
  `firma` TINYINT(1) NULL DEFAULT NULL,
  `registro` TINYINT(1) NULL DEFAULT NULL,
  `tipo_firma` VARCHAR(45) NULL DEFAULT NULL,
  `csv` TINYINT(1) NULL DEFAULT NULL,
  `tipo_documentos_id` INT(11) NOT NULL,
  `acuse` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`, `tipo_documentos_id`),
  INDEX `fk_documentos_tipo_documentos1_idx` (`tipo_documentos_id` ASC),
  CONSTRAINT `fk_documentos_tipo_documentos1`
    FOREIGN KEY (`tipo_documentos_id`)
    REFERENCES `correo`.`tipo_documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`publicaciones` ;

CREATE TABLE IF NOT EXISTS `correo`.`publicaciones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `num_publicacion` VARCHAR(45) NULL DEFAULT NULL,
  `enviado` DATETIME NULL DEFAULT NULL,
  `bloqueo` TINYINT(1) NULL DEFAULT '0',
  `fecha_publicacion` DATETIME NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `correo`.`usuarios` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(80) NOT NULL,
  `password` VARCHAR(120) NOT NULL,
  `nombre` VARCHAR(120) NULL DEFAULT NULL,
  `apellidos` VARCHAR(180) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `siglas` VARCHAR(10) NOT NULL,
  `telefono` VARCHAR(9) NULL DEFAULT NULL,
  `pd` TINYINT(1) NULL DEFAULT '0',
  `jefatura` VARCHAR(120) NULL DEFAULT NULL,
  `firma` TINYINT(1) NULL DEFAULT '0',
  `unidades_id` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`, `unidades_id`),
  INDEX `fk_usuarios_unidades1_idx` (`unidades_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `correo`.`bop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`bop` ;

CREATE TABLE IF NOT EXISTS `correo`.`bop` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(45) NOT NULL,
  `expediente` VARCHAR(45) NOT NULL,
  `fecha_envio` DATETIME NULL DEFAULT NULL,
  `relacion_contribuyente` VARCHAR(45) NOT NULL,
  `num_bop` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_publicacion` DATETIME NULL DEFAULT NULL,
  `fecha_grabacion` DATETIME NULL DEFAULT NULL,
  `contribuyente` VARCHAR(255) NULL DEFAULT NULL,
  `nif_contribuyente` VARCHAR(15) NULL DEFAULT NULL,
  `documentos_id` VARCHAR(10) NOT NULL,
  `usuarios_id` BIGINT(20) NOT NULL,
  `orden` BIGINT(20) UNSIGNED NOT NULL,
  `notificar_bop` TINYINT(1) NULL DEFAULT NULL,
  `notificar_boe` TINYINT(1) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(120) NULL DEFAULT NULL,
  `publicaciones_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `documentos_id`, `usuarios_id`, `publicaciones_id`),
  INDEX `fk_bop_documentos1_idx` (`documentos_id` ASC),
  INDEX `fk_bop_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_bop_publicaciones1_idx` (`publicaciones_id` ASC),
  CONSTRAINT `fk_bop_documentos1`
    FOREIGN KEY (`documentos_id`)
    REFERENCES `correo`.`documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bop_publicaciones1`
    FOREIGN KEY (`publicaciones_id`)
    REFERENCES `correo`.`publicaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bop_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `correo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`departamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`departamentos` ;

CREATE TABLE IF NOT EXISTS `correo`.`departamentos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`tipos_incidencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`tipos_incidencia` ;

CREATE TABLE IF NOT EXISTS `correo`.`tipos_incidencia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`devoluciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`devoluciones` ;

CREATE TABLE IF NOT EXISTS `correo`.`devoluciones` (
  `codigo_barras` VARCHAR(23) NOT NULL,
  `observaciones` LONGTEXT NOT NULL,
  `fecha_notificada` DATETIME NULL DEFAULT NULL,
  `fecha_entrada` DATETIME NULL DEFAULT NULL,
  `fecha_devuelta` DATETIME NULL DEFAULT NULL,
  `tipos_incidencia_id` INT(11) NOT NULL,
  PRIMARY KEY (`codigo_barras`, `tipos_incidencia_id`),
  INDEX `fk_devoluciones_tipos_incidencia1_idx` (`tipos_incidencia_id` ASC),
  CONSTRAINT `fk_devoluciones_tipos_incidencia1`
    FOREIGN KEY (`tipos_incidencia_id`)
    REFERENCES `correo`.`tipos_incidencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`provincias` ;

CREATE TABLE IF NOT EXISTS `correo`.`provincias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`localidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`localidades` ;

CREATE TABLE IF NOT EXISTS `correo`.`localidades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `provincias_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `provincias_id`),
  INDEX `fk_poblaciones_provincias1_idx` (`provincias_id` ASC),
  CONSTRAINT `fk_poblaciones_provincias1`
    FOREIGN KEY (`provincias_id`)
    REFERENCES `correo`.`provincias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8122
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`remesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`remesas` ;

CREATE TABLE IF NOT EXISTS `correo`.`remesas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `num_remesa` VARCHAR(45) NOT NULL,
  `enviado` DATETIME NULL DEFAULT NULL,
  `bloqueo` TINYINT(1) NULL DEFAULT '0',
  `p1` VARCHAR(45) NULL DEFAULT NULL,
  `p2` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_devolucion` DATETIME NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`tipo_via`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`tipo_via` ;

CREATE TABLE IF NOT EXISTS `correo`.`tipo_via` (
  `id` VARCHAR(3) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `nombre_corto` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`diario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`diario` ;

CREATE TABLE IF NOT EXISTS `correo`.`diario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ano` VARCHAR(5) NOT NULL,
  `cbar` VARCHAR(45) NOT NULL,
  `cbarpf` VARCHAR(45) NULL DEFAULT NULL,
  `cbarrec` VARCHAR(45) NULL DEFAULT NULL,
  `expediente` VARCHAR(45) NULL DEFAULT NULL,
  `referencia` VARCHAR(45) NULL DEFAULT NULL,
  `nif` VARCHAR(15) NOT NULL DEFAULT '*** ***',
  `contribuyente` VARCHAR(255) NOT NULL,
  `domicilio` VARCHAR(255) NOT NULL,
  `cod_postal` VARCHAR(5) NOT NULL,
  `fecha_grabacion` DATETIME NOT NULL,
  `fecha_envio` DATETIME NULL DEFAULT NULL,
  `fecha_recepcion` DATETIME NULL DEFAULT NULL,
  `pdfs` LONGTEXT NULL DEFAULT NULL,
  `observaciones` LONGTEXT NOT NULL,
  `text_com_1` LONGTEXT NULL DEFAULT NULL,
  `text_com_2` LONGTEXT NULL DEFAULT NULL,
  `text_com_3` LONGTEXT NULL DEFAULT NULL,
  `cabecera_1` LONGTEXT NULL DEFAULT NULL,
  `cabecera_2` LONGTEXT NULL DEFAULT NULL,
  `cabecera_3` LONGTEXT NULL DEFAULT NULL,
  `pie_reposicion` LONGTEXT NULL DEFAULT NULL,
  `pie_devolucion` LONGTEXT NULL DEFAULT NULL,
  `pie_rectificacion` LONGTEXT NULL DEFAULT NULL,
  `pie_nulidad` LONGTEXT NULL DEFAULT NULL,
  `pie_revocacion` LONGTEXT NULL DEFAULT NULL,
  `c1` INT(11) NULL DEFAULT NULL,
  `c2` INT(11) NULL DEFAULT NULL,
  `p1` INT(11) NULL DEFAULT NULL,
  `p2` INT(11) NULL DEFAULT NULL,
  `p3` INT(11) NULL DEFAULT NULL,
  `p4` INT(11) NULL DEFAULT NULL,
  `p5` INT(11) NULL DEFAULT NULL,
  `firma` TINYINT(1) NULL DEFAULT NULL,
  `pd` TINYINT(1) NULL DEFAULT NULL,
  `titulo` LONGTEXT NULL DEFAULT NULL,
  `sello` TINYINT(1) NULL DEFAULT NULL,
  `remesas_id` INT(11) NOT NULL,
  `usuarios_id` BIGINT(20) NOT NULL,
  `documentos_id` VARCHAR(10) NOT NULL,
  `tipos_incidencia_id` INT(11) NOT NULL DEFAULT '0',
  `tipo_via_id` VARCHAR(3) NOT NULL,
  `provincias_id` INT(11) NOT NULL,
  `localidades_id` INT(11) NOT NULL,
  `cbmaccleber` VARCHAR(23) NULL DEFAULT NULL,
  `centro_impresion` TINYINT(1) NULL DEFAULT '0',
  `notifica_entrega` TINYINT(1) NULL DEFAULT '0',
  `notifica_bop` TINYINT(1) NULL DEFAULT '0',
  `notifica_boe` TINYINT(1) NULL DEFAULT '0',
  `orden` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `remesas_id`, `usuarios_id`, `documentos_id`, `tipos_incidencia_id`, `tipo_via_id`, `provincias_id`, `localidades_id`),
  INDEX `fk_diario_remesas1_idx` (`remesas_id` ASC),
  INDEX `fk_diario_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_diario_documentos1_idx` (`documentos_id` ASC),
  INDEX `fk_diario_tipos_incidencia1_idx` (`tipos_incidencia_id` ASC),
  INDEX `fk_diario_tipo_via1_idx` (`tipo_via_id` ASC),
  INDEX `fk_diario_provincias1_idx` (`provincias_id` ASC),
  INDEX `fk_diario_localidades1_idx` (`localidades_id` ASC),
  CONSTRAINT `fk_diario_documentos1`
    FOREIGN KEY (`documentos_id`)
    REFERENCES `correo`.`documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diario_localidades1`
    FOREIGN KEY (`localidades_id`)
    REFERENCES `correo`.`localidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diario_provincias1`
    FOREIGN KEY (`provincias_id`)
    REFERENCES `correo`.`provincias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diario_remesas1`
    FOREIGN KEY (`remesas_id`)
    REFERENCES `correo`.`remesas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diario_tipo_via1`
    FOREIGN KEY (`tipo_via_id`)
    REFERENCES `correo`.`tipo_via` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diario_tipos_incidencia1`
    FOREIGN KEY (`tipos_incidencia_id`)
    REFERENCES `correo`.`tipos_incidencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diario_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `correo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`unidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`unidades` ;

CREATE TABLE IF NOT EXISTS `correo`.`unidades` (
  `id` VARCHAR(3) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `departamentos_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `departamentos_id`),
  INDEX `fk_unidades_departamentos1_idx` (`departamentos_id` ASC),
  CONSTRAINT `fk_unidades_departamentos1`
    FOREIGN KEY (`departamentos_id`)
    REFERENCES `correo`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`documentos_has_unidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`documentos_has_unidades` ;

CREATE TABLE IF NOT EXISTS `correo`.`documentos_has_unidades` (
  `documentos_id` VARCHAR(10) NOT NULL,
  `unidades_id` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`documentos_id`, `unidades_id`),
  INDEX `fk_documentos_has_unidades_unidades1_idx` (`unidades_id` ASC),
  INDEX `fk_documentos_has_unidades_documentos1_idx` (`documentos_id` ASC),
  CONSTRAINT `fk_documentos_has_unidades_documentos1`
    FOREIGN KEY (`documentos_id`)
    REFERENCES `correo`.`documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_has_unidades_unidades1`
    FOREIGN KEY (`unidades_id`)
    REFERENCES `correo`.`unidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`ficheros_procesados_ftp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`ficheros_procesados_ftp` ;

CREATE TABLE IF NOT EXISTS `correo`.`ficheros_procesados_ftp` (
  `arbol` VARCHAR(30) NOT NULL,
  `ruta_fichero` VARCHAR(100) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  PRIMARY KEY (`arbol`, `ruta_fichero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`historico_diario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`historico_diario` ;

CREATE TABLE IF NOT EXISTS `correo`.`historico_diario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ano` VARCHAR(5) NOT NULL,
  `cbar` VARCHAR(45) NOT NULL,
  `cbarpf` VARCHAR(45) NULL DEFAULT NULL,
  `cbarrec` VARCHAR(45) NULL DEFAULT NULL,
  `expediente` VARCHAR(45) NULL DEFAULT NULL,
  `referencia` VARCHAR(45) NULL DEFAULT NULL,
  `nif` VARCHAR(15) NOT NULL DEFAULT '*** ***',
  `contribuyente` VARCHAR(255) NOT NULL,
  `domicilio` VARCHAR(255) NOT NULL,
  `cod_postal` VARCHAR(5) NOT NULL,
  `fecha_grabacion` DATETIME NOT NULL,
  `fecha_envio` DATETIME NOT NULL,
  `fecha_recepcion` DATETIME NULL DEFAULT NULL,
  `pdfs` LONGTEXT NULL DEFAULT NULL,
  `observaciones` LONGTEXT NOT NULL,
  `text_com_1` LONGTEXT NULL DEFAULT NULL,
  `text_com_2` LONGTEXT NULL DEFAULT NULL,
  `text_com_3` LONGTEXT NULL DEFAULT NULL,
  `cabecera_1` LONGTEXT NULL DEFAULT NULL,
  `cabecera_2` LONGTEXT NULL DEFAULT NULL,
  `cabecera_3` LONGTEXT NULL DEFAULT NULL,
  `pie_reposicion` LONGTEXT NULL DEFAULT NULL,
  `pie_devolucion` LONGTEXT NULL DEFAULT NULL,
  `pie_rectificacion` LONGTEXT NULL DEFAULT NULL,
  `pie_nulidad` LONGTEXT NULL DEFAULT NULL,
  `pie_revocacion` LONGTEXT NULL DEFAULT NULL,
  `c1` INT(11) NULL DEFAULT NULL,
  `c2` INT(11) NULL DEFAULT NULL,
  `p1` INT(11) NULL DEFAULT NULL,
  `p2` INT(11) NULL DEFAULT NULL,
  `p3` INT(11) NULL DEFAULT NULL,
  `p4` INT(11) NULL DEFAULT NULL,
  `p5` INT(11) NULL DEFAULT NULL,
  `firma` TINYINT(1) NULL DEFAULT NULL,
  `pd` TINYINT(1) NULL DEFAULT NULL,
  `titulo` LONGTEXT NULL DEFAULT NULL,
  `sello` TINYINT(1) NULL DEFAULT NULL,
  `remesas_id` INT(11) NOT NULL,
  `usuarios_id` BIGINT(20) NOT NULL,
  `documentos_id` VARCHAR(10) NOT NULL,
  `tipos_incidencia_id` INT(11) NOT NULL DEFAULT '0',
  `tipo_via_id` VARCHAR(3) NOT NULL,
  `provincias_id` INT(11) NOT NULL,
  `localidades_id` INT(11) NOT NULL,
  `cbmaccleber` VARCHAR(23) NULL DEFAULT NULL,
  `centro_impresion` TINYINT(1) NULL DEFAULT '0',
  `notifica_entrega` TINYINT(1) NULL DEFAULT '0',
  `notifica_bop` TINYINT(1) NULL DEFAULT '0',
  `notifica_boe` TINYINT(1) NULL DEFAULT '0',
  `orden` BIGINT(20) UNSIGNED NOT NULL,
  `fecha_envio_bop` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `remesas_id`, `usuarios_id`, `documentos_id`, `tipos_incidencia_id`, `tipo_via_id`, `provincias_id`, `localidades_id`),
  INDEX `fk_historico_diario_remesas1_idx` (`remesas_id` ASC),
  INDEX `fk_historico_diario_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_historico_diario_documentos1_idx` (`documentos_id` ASC),
  INDEX `fk_historico_diario_tipos_incidencia1_idx` (`tipos_incidencia_id` ASC),
  INDEX `fk_historico_diario_tipo_via1_idx` (`tipo_via_id` ASC),
  INDEX `fk_historico_diario_provincias1_idx` (`provincias_id` ASC),
  INDEX `fk_historico_diario_localidades1_idx` (`localidades_id` ASC),
  CONSTRAINT `fk_historico_diario_documentos1`
    FOREIGN KEY (`documentos_id`)
    REFERENCES `correo`.`documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_diario_localidades1`
    FOREIGN KEY (`localidades_id`)
    REFERENCES `correo`.`localidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_diario_provincias1`
    FOREIGN KEY (`provincias_id`)
    REFERENCES `correo`.`provincias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_diario_remesas1`
    FOREIGN KEY (`remesas_id`)
    REFERENCES `correo`.`remesas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_diario_tipo_via1`
    FOREIGN KEY (`tipo_via_id`)
    REFERENCES `correo`.`tipo_via` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_diario_tipos_incidencia1`
    FOREIGN KEY (`tipos_incidencia_id`)
    REFERENCES `correo`.`tipos_incidencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_diario_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `correo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`historico_bop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`historico_bop` ;

CREATE TABLE IF NOT EXISTS `correo`.`historico_bop` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(45) NOT NULL,
  `expediente` VARCHAR(45) NOT NULL,
  `fecha_envio` DATETIME NOT NULL,
  `relacion_contribuyente` VARCHAR(45) NOT NULL,
  `num_bop` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_publicacion` DATETIME NULL DEFAULT NULL,
  `fecha_grabacion` DATETIME NULL DEFAULT NULL,
  `contribuyente` VARCHAR(255) NULL DEFAULT NULL,
  `nif_contribuyente` VARCHAR(15) NULL DEFAULT NULL,
  `documentos_id` VARCHAR(10) NOT NULL,
  `usuarios_id` BIGINT(20) NOT NULL,
  `orden` BIGINT(20) UNSIGNED NOT NULL,
  `notificar_bop` TINYINT(1) NULL DEFAULT NULL,
  `notificar_boe` TINYINT(1) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(120) NULL DEFAULT NULL,
  `publicaciones_id` INT(11) NOT NULL,
  `cbmaccleber` VARCHAR(23) NULL DEFAULT NULL,
  `historico_diario_id` INT(11) NULL,
  PRIMARY KEY (`id`, `documentos_id`, `usuarios_id`, `publicaciones_id`),
  INDEX `fk_historico_bop_documentos1_idx` (`documentos_id` ASC),
  INDEX `fk_historico_bop_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_historico_bop_publicaciones1_idx` (`publicaciones_id` ASC),
  INDEX `fk_historico_bop_historico_diario1_idx` (`historico_diario_id` ASC),
  CONSTRAINT `fk_historico_bop_documentos1`
    FOREIGN KEY (`documentos_id`)
    REFERENCES `correo`.`documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_bop_publicaciones1`
    FOREIGN KEY (`publicaciones_id`)
    REFERENCES `correo`.`publicaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_bop_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `correo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_bop_historico_diario1`
    FOREIGN KEY (`historico_diario_id`)
    REFERENCES `correo`.`historico_diario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `correo`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`roles` ;

CREATE TABLE IF NOT EXISTS `correo`.`roles` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `correo`.`usuarios_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `correo`.`usuarios_roles` ;

CREATE TABLE IF NOT EXISTS `correo`.`usuarios_roles` (
  `usuarios_id` BIGINT(20) NOT NULL,
  `roles_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`usuarios_id`, `roles_id`),
  INDEX `fk_usuarios_has_roles_roles1_idx` (`roles_id` ASC),
  INDEX `fk_usuarios_has_roles_usuarios_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_usuarios_has_roles_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `correo`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_roles_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `correo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
